### ISSUE TITLE
Please provide adjusted redisflaski source

### ISSUE THREAD

**Issue by waja** [DevOps-Academy-Org/kubernetes-workshop#10]
index.md#a-more-sophisticated-application references a redis adjusted flaski app. But I wasn't able to find it. It would be great to get that available.

Thanks, Jan.

**Comment by McSlow** [comment]
Hi Jan, sorry, perhaps i forgot to mention that: It's here https://github.com/McSlow/k8s_flask  - and it's the redis branch of that git repo. So... https://github.com/McSlow/k8s_flask/tree/redis :)
So perhaps you already have it and just need to switch the branch (git checkout redis)
